/**
 * Fetches the LiteDAW type stack from Google Fonts and vendors it into public/fonts.
 * Keeps only latin + latin-ext subsets so the app works fully offline (Capacitor / PWA).
 *
 *   node scripts/fetch-fonts.mjs
 */
import { mkdir, writeFile, readFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';

const ROOT = path.resolve(import.meta.dirname, '..');
const OUT_DIR = path.join(ROOT, 'public', 'fonts');

const FAMILIES = [
  'Chakra+Petch:wght@400;500;600;700',
  'Barlow:wght@400;500;600;700',
  'Barlow+Condensed:wght@400;500;600;700',
  'Share+Tech+Mono',
];

const KEEP_SUBSETS = new Set(['latin', 'latin-ext']);
const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36';

async function main() {
  await mkdir(OUT_DIR, { recursive: true });
  const url = `https://fonts.googleapis.com/css2?${FAMILIES.map((f) => `family=${f}`).join('&')}&display=swap`;
  const css = await (await fetch(url, { headers: { 'User-Agent': UA } })).text();

  const blocks = css.split('/*').slice(1);
  const out = [
    '/* LiteDAW vendored type stack — generated by scripts/fetch-fonts.mjs */',
    '/* Chakra Petch (display) · Barlow (UI) · Barlow Condensed (labels) · Share Tech Mono (readouts) */',
    '',
  ];
  let downloaded = 0;

  for (const block of blocks) {
    const subset = block.slice(0, block.indexOf('*/')).trim();
    if (!KEEP_SUBSETS.has(subset)) continue;
    const body = block.slice(block.indexOf('*/') + 2);
    const face = body.slice(body.indexOf('@font-face'), body.indexOf('}', body.indexOf('@font-face')) + 1);
    if (!face) continue;

    const srcMatch = face.match(/url\((https:\/\/[^)]+\.woff2)\)/);
    if (!srcMatch) continue;
    const remote = srcMatch[1];

    const family = face.match(/font-family:\s*'([^']+)'/)?.[1] ?? 'font';
    const weight = face.match(/font-weight:\s*(\d+)/)?.[1] ?? '400';
    const slug = `${family.toLowerCase().replace(/\s+/g, '-')}-${weight}-${subset}.woff2`;
    const dest = path.join(OUT_DIR, slug);

    if (!existsSync(dest)) {
      const buf = Buffer.from(await (await fetch(remote, { headers: { 'User-Agent': UA } })).arrayBuffer());
      await writeFile(dest, buf);
      downloaded++;
    }

    out.push(
      face
        .replace(/src:\s*url\([^)]+\)\s*format\('woff2'\);/, `src: url('./${slug}') format('woff2');`)
        .replace(/\n\s+/g, '\n  ')
        .trim(),
      '',
    );
  }

  await writeFile(path.join(OUT_DIR, 'fonts.css'), out.join('\n'), 'utf8');
  console.log(`fonts.css written · ${out.filter((l) => l.startsWith('@font-face')).length} faces · ${downloaded} new files`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
